import { Inter } from "next/font/google"

import type { Metadata } from "next"

import { Providers } from "@/providers"

import "@/styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
